#!/bin/bash

#echo $0
echo $1
echo $2

#cat  $1
#cat  $2

a=$(awk 'END{print NR}' $1)
b=$(awk 'END{print NR}' $2)
c=0

if((a > b))
then
	c=a
else
	c=b
fi

for((i=1;i<=$c;i++))
do
	if [ "$(awk -v f=$i 'NR==f {print $0}' $1)" != "$(awk -v f=$i 'NR==f {print $0}' $2)" ]
	then
		echo -e "\ndifferent line number = $i"
		break 
	fi
done

#red='\033[0;31m'
#nc='\033[0m'

awk -v n=$i 'NR==0,NR==n {print NR,$0}' $1
l1="$(awk -v n=$i 'NR==n {print NR,$0}' $1)"
echo -e "\033[0;31m${l1}\033[0m"
awk -v n=$i -v m=$a 'NR==n,NR==m {print NR,$0}' $1
echo -e "In $1 and\n\n"

l2="$(awk -v n=$i 'NR==n {print NR,$0}' $2)"
awk -v n=$i 'NR==0,NR==n {print NR,$0}' $2
echo -e "\033[0;31m${l2}\033[0m"
awk -v n=$i -v m=$b 'NR==n,NR==m {print NR,$0}' $2
echo -e "In $2"

if((c == a))
then
	start=$((a-b+1))
	file=$1
	end=$a
else
	start=$((b-a+1))
	file=$2
	end=$b
fi

echo -e "\nextra lines in $file : \033[0;32m"
awk -v start=$start -v end=$end 'NR==start,NR==end {print NR,$0}' $file
echo -e '\033[0m'



